WAILS := $(shell go env GOPATH)/bin/wails

# ── App ──────────────────────────────────────────────────────────────────────

.PHONY: dev
dev:          ## Run the app in development mode (hot-reload)
	$(WAILS) dev

.PHONY: build
build:        ## Build macOS production app into build/bin/
	$(WAILS) build -platform darwin/amd64

.PHONY: build-windows
build-windows: ## Cross-compile Windows .exe into build/bin/  (requires: brew install mingw-w64)
	CC=x86_64-w64-mingw32-gcc $(WAILS) build -platform windows/amd64

.PHONY: build-all
build-all:    ## Build both macOS and Windows into build/bin/
	$(WAILS) build -platform darwin/amd64
	CC=x86_64-w64-mingw32-gcc $(WAILS) build -platform windows/amd64

.PHONY: release
release: build-all  ## Build both platforms and package into build/release/
	mkdir -p build/release
	cd build/bin && zip -r ../release/PhotoCaption-mac.zip PhotoCaption.app
	cd build/bin && zip -r ../release/PhotoCaption-windows.zip PhotoCaption.exe

# make release
# gh release create v0.1.0 \
#   build/release/PhotoCaption-mac.zip \
#   build/release/PhotoCaption-windows.zip \
#   --title "v0.1.0" --notes "Initial release"

.PHONY: build-debug
build-debug:  ## Build with debug symbols and devtools enabled
	$(WAILS) build -debug -devtools

.PHONY: clean
clean:        ## Remove build artefacts
	rm -rf build/bin

# ── Go tooling ───────────────────────────────────────────────────────────────

.PHONY: tidy
tidy:         ## Tidy go.mod / go.sum
	go mod tidy

.PHONY: vet
vet:          ## Run go vet
	go vet ./...

# ── Debugging ────────────────────────────────────────────────────────────────

.PHONY: debug-server
debug-server: ## Build debug bundle, then start Delve on :2345 for VSCode attach
	$(WAILS) build -debug -devtools
	dlv exec --headless --listen=:2345 --api-version=2 --accept-multiclient \
		./build/bin/PhotoCaption.app/Contents/MacOS/PhotoCaption

# ── Project tools ────────────────────────────────────────────────────────────

.PHONY: notices
notices:      ## Regenerate NOTICES.md with third-party license info
	@which go-licenses > /dev/null 2>&1 || go install github.com/google/go-licenses@latest
	@printf '# Third-Party Licenses\n\nGenerated by [go-licenses](https://github.com/google/go-licenses).\n\n| Package | License URL | Type |\n|---------|-------------|------|\n' > NOTICES.md
	@go-licenses report . 2>/dev/null | awk -F',' '{print "| " $$1 " | " $$2 " | " $$3 " |"}' >> NOTICES.md
	@echo "NOTICES.md updated."


.PHONY: exifdump
exifdump:     ## Print all EXIF tags from an image  usage: make exifdump FILE=photo.jpg
ifndef FILE
	$(error FILE is required — usage: make exifdump FILE=path/to/image.jpg)
endif
	go run ./cmd/exifdump "$(FILE)"

# ── Help ─────────────────────────────────────────────────────────────────────

.PHONY: help
help:         ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

.DEFAULT_GOAL := help
